<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.251">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Revictimization: a misogyny detection problem - Results</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">Revictimization: a misogyny detection problem</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./about.html">Authors</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./repository.html">Repository</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-data" role="button" data-bs-toggle="dropdown" aria-expanded="false">Data</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-data">    
        <li>
    <a class="dropdown-item" href="./data.html">
 <span class="dropdown-text">Data</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./data_collection.html">
 <span class="dropdown-text">Data collection</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./data_labeling.html">
 <span class="dropdown-text">Data labeling</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./data_cleaning.html">
 <span class="dropdown-text">Data cleaning</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-classification" role="button" data-bs-toggle="dropdown" aria-expanded="false">Classification</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-classification">    
        <li>
    <a class="dropdown-item" href="./classification.html">
 <span class="dropdown-text">Classification</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./nb.html">
 <span class="dropdown-text">Naive Bayes</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./bert.html">
 <span class="dropdown-text">BERT</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link active" href="./results.html" aria-current="page">Results</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./bot.html">Detection Bot</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#results" id="toc-results" class="nav-link active" data-scroll-target="#results">Results</a>
  <ul class="collapse">
  <li><a href="#prediction-of-tweets-results" id="toc-prediction-of-tweets-results" class="nav-link" data-scroll-target="#prediction-of-tweets-results">Prediction of tweets results</a></li>
  <li><a href="#prediction-of-articles-results" id="toc-prediction-of-articles-results" class="nav-link" data-scroll-target="#prediction-of-articles-results">Prediction of articles results</a></li>
  </ul></li>
  <li><a href="#conclusions-and-future-work" id="toc-conclusions-and-future-work" class="nav-link" data-scroll-target="#conclusions-and-future-work">Conclusions and Future Work</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Results</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<section id="results" class="level1">
<h1>Results</h1>
<p>Multiple supeprvised classifier were trained with 2 different sets, one of tweets and the other one of news articles, both generated in México.</p>
<section id="prediction-of-tweets-results" class="level3">
<h3 class="anchored" data-anchor-id="prediction-of-tweets-results">Prediction of tweets results</h3>
<p>Since the tweets were labeled it was possible to calculate the accuracy of the model by sampling the set into a training and testing set.</p>
<table class="table">
<colgroup>
<col style="width: 35%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 20%">
<col style="width: 16%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Epochs</th>
<th>Accuracy</th>
<th>Loss</th>
<th>Validated Accuracy</th>
<th>Validated Loss</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>bert_uncased (BERT)</td>
<td>2</td>
<td>0.9227</td>
<td>0.1999</td>
<td>0.8185</td>
<td>0.5404</td>
</tr>
<tr class="even">
<td></td>
<td>3</td>
<td>0.9919</td>
<td>0.0211</td>
<td>0.8445</td>
<td>0.846</td>
</tr>
<tr class="odd">
<td>pysentimiento (roBERTa)</td>
<td>2</td>
<td>0.9088</td>
<td>0.2434</td>
<td>0.8066</td>
<td>0.5107</td>
</tr>
<tr class="even">
<td></td>
<td>3</td>
<td>0.9859</td>
<td>0.0449</td>
<td>0.8166</td>
<td>0.9603</td>
</tr>
<tr class="odd">
<td>bert_multilingual_uncased (BERT)</td>
<td>2</td>
<td>0.9457</td>
<td>0.146</td>
<td>0.8445</td>
<td>0.5849</td>
</tr>
<tr class="even">
<td></td>
<td>3</td>
<td>0.9899</td>
<td>0.0279</td>
<td><strong>0.8634</strong></td>
<td>0.6502</td>
</tr>
<tr class="odd">
<td>Naive Bayes</td>
<td>-</td>
<td>0.8253</td>
<td>-</td>
<td>0.7796</td>
<td>-</td>
</tr>
<tr class="even">
<td>KNN</td>
<td>-</td>
<td>0.8606</td>
<td>-</td>
<td>0.6669</td>
<td>-</td>
</tr>
</tbody>
</table>
<p>The results demonstrate how transformers outstand classic models such as Naive Bayes or KNN. After training with a set of almost 8,000 tweets and testing with 2,000 the best accuracy of 86.34% was obtained with BERT multilingual uncased trained with 3 epochs. Followed by BERT uncased with the same number of epochs.</p>
<p>Another interesting result obtained during data exploration is KNN having the best accuracy of 69% with 30 neighbors.</p>
</section>
<section id="prediction-of-articles-results" class="level3">
<h3 class="anchored" data-anchor-id="prediction-of-articles-results">Prediction of articles results</h3>
<p>Furthermore, although the results of article’s prediction are shown in the next table, the model’s results might not be accurate given the small number of labeled articles (120) to evaluate.</p>
<table class="table">
<colgroup>
<col style="width: 34%">
<col style="width: 8%">
<col style="width: 19%">
<col style="width: 8%">
<col style="width: 21%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Model</th>
<th>Epochs</th>
<th>Trained on Tweets</th>
<th></th>
<th>Trained on Articles</th>
<th></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td></td>
<td></td>
<td>Accuracy</td>
<td>Loss</td>
<td>Accuracy</td>
<td>Loss</td>
</tr>
<tr class="even">
<td>bert_uncased (BERT)</td>
<td>2</td>
<td>0.9217</td>
<td>0.1998</td>
<td>0.911</td>
<td>0.319</td>
</tr>
<tr class="odd">
<td></td>
<td>3</td>
<td></td>
<td></td>
<td>0.6525</td>
<td>0.6171</td>
</tr>
<tr class="even">
<td>pysentimiento (roBERTa)</td>
<td>2</td>
<td>0.8999</td>
<td>0.2516</td>
<td>0.589</td>
<td>0.6878</td>
</tr>
<tr class="odd">
<td></td>
<td>3</td>
<td></td>
<td></td>
<td>0.5805</td>
<td>0.6864</td>
</tr>
<tr class="even">
<td>bert_multilingual_uncased (BERT)</td>
<td>2</td>
<td><strong>0.9473</strong></td>
<td>0.1469</td>
<td>0.678</td>
<td>0.6106</td>
</tr>
<tr class="odd">
<td></td>
<td>3</td>
<td></td>
<td></td>
<td><strong>0.9449</strong></td>
<td>0.3233</td>
</tr>
</tbody>
</table>
<p>The best accuracy for predicting articles was 94.73% after training a bert_multilingual_uncased model with labeled tweets followed by a close result of 94.49% after training the same model with articles and one more epoch.</p>
<p>To have a better understanding of the model’s performances we compared the balance of predictions by class:</p>
<table class="table">
<thead>
<tr class="header">
<th>model&nbsp;</th>
<th>Misogynistic</th>
<th>Non - misogynistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>bert_uncased trained news&nbsp;</td>
<td>6810</td>
<td>1120</td>
</tr>
<tr class="even">
<td>pysentimiento fine-tune news</td>
<td>6810</td>
<td>1120</td>
</tr>
<tr class="odd">
<td>bert_multilingual news</td>
<td>5335</td>
<td>2595</td>
</tr>
<tr class="even">
<td>bert_multilingual tweets</td>
<td>7443</td>
<td>487</td>
</tr>
<tr class="odd">
<td>pysentimiento fine-tune tweets</td>
<td>7916</td>
<td>14</td>
</tr>
<tr class="even">
<td>bert_uncased trained tweets</td>
<td>7448</td>
<td>482</td>
</tr>
</tbody>
</table>
<p>By looking at the balance we can see all models behave in the same way predicting more misogynistic articles than noon-misogynistic. Since those articles are not labeled there is no way to know if the models are overfitted or there are actually more articles that are misogynistic.</p>
<p>Although the articles might be misogynistic the table shows that the models trained with tweets tend to classify articles into the mentioned class.</p>
<p>Finally, as part of the results an analysis of the predictions with the best model was performed:</p>
<table class="table">
<colgroup>
<col style="width: 44%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Predicted as misogynistic</th>
<th>Predicted as non-misogynistic</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>ACAPULCO, Gro., 23 de marzo de 2016.- Dos mujeres fueron asesinadas a balazos y un hombre quedó herido en un tianguis ubicado en el bulevar Vicente Guerrero de este puerto. Los hechos se registraron a las 18:45 horas, cuando hombres dispararon en contra de las mujeres comerciantes, quienes murieron al instante y donde quedó herido el individuo en la calle 1 de la colonia Postal. Una de las víctimas vestía pantalón café, blusa roja y estaba descalza y la otra tenía camiseta verde, pantalón verde con dibujos y tenis blancos. El hombre herido fue trasladado a un hospital para su atención médica inmediata.</td>
<td>Guerrero, México; 10 de mayo 2016.-En pleno día de las madres y en medio de la exigencia por un alto a los feminicidios localizan a una joven dama, descuartizada, y envuelta en una sabana en la colonia 6 de enero del violento Acapulco. Autoridades informaron que fueron alertados sobre la presencia del cadáver mediante una llamada anónimo. Peritos del estado establecieron que cuando llegaron al sitio indicado encontraron envueltos en sabanas, un par de piernas, un par de brazos, un torso femenino y una cabeza, todas las partes humanas pertenecían a la misma fémina, la cual no ha sido identificada. Las partes fueron recolectadas por la autoridad y lo trasladaron al SEMEFO de la ciudad, para realizar la necropsia de ley y esperar a que sea identificada</td>
</tr>
</tbody>
</table>
</section>
</section>
<section id="conclusions-and-future-work" class="level1">
<h1>Conclusions and Future Work</h1>
<p>Through this work, we collected, cleaned, and transformed data from different sources to attack a vital problem occurring in Latin America, revictimization performed by communication platforms. Given the lack of data labeled for this work, the objective was to evaluate the performance of a model trained to detect a particular type of misogyny (misogyny in social media) to classify a different type (revictimization in news articles).</p>
<p>The results of this work show how BERT outperforms traditional models, although its main disadvantage is the amount of data and computational efficiency needed for training the model. Through this work, we ran and evaluated models on a personal computer, such as Multinomial Naive Bayes and K-nearest Neighbours. Unfortunately, external resources such as Google Colab pro had to be reached to fine-tune all BERT pre-trained models. Furthermore, running the three pre-trained models in the results sections cost ~100 GPUs (10 USD). The cost of performing this task shows that we are still far from accessible knowledge in the NLP field.</p>
<p>Besides efficiency, the pre-trained models demonstrated high accuracy in predicting the label of both tweets and news articles. For the prediction of both tweets and articles, bert_multilingual_uncased obtained the highest accuracy of 86% and 94% each. As mentioned previously, these values might not be reliable, given the nature of the data. However, as a baseline comparison, we can look at the F1-score displayed in the hugging face library documentation for models such as roBERTA and roBERTuito (pysentimiento), which are 67% and 70.5% for their sentiment analysis task. We can also assume that our models provide a higher performance because of the fine-tuning with our set. For example, although pysentimiento is trained with tweets in Spanish (which might be close to our tweets set), those contain different dialects in Spanish, increasing the number of features (words) and even semantics of texts that do not align with our data. Finally, after comparing the balance of the predictions of models trained with tweets, we detected that the models were overfitted to the “misogynistic” class. This leads to the assumption that misogyny in tweets or natural conversations is not modeled similarly to revictimization.</p>
<p>Furthermore, an exciting result is a prediction made by multilingual_bert_uncased. The model could detect an example of an article with subtle misogyny. Additionally, it detected an article describing femicide without misogynistic opinions as not misogynistic. The good accuracies and results from the models provide insight into how an automatic classifier can attack the revictimization problem in communication platforms.</p>
<p>Future work can be performed to:</p>
<ul>
<li><p>Label datasets or evaluate all the generated predictions from this work to continue training more efficient models with labeled data and measure its predictions effectively.</p></li>
<li><p>Gather information in English to compare the results of misogyny in both languages.</p></li>
<li><p>Provide a server to our bot to continuously collect information and serve as a guide to detect revictimization.</p></li>
</ul>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->



</body></html>