project:
  type: website

website:
  title: "Revictimization: a misogyny detection problem"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - repository.qmd
      - sidebar:data
      - sidebar:classification
      - results.qmd
      - bot.qmd
  sidebar:
    - id: data
      title: "Data"
      contents:
      - data.qmd
      - data_collection.qmd
      - data_labeling.qmd
      - data_cleaning.qmd
    - id: classification
      title: "Classification"
      contents:
      - classification.qmd
      - nb.qmd
      - bert.qmd
format:
  html:
    css: styles.css
    theme: 
    - zephyr
    - custom.scss
     
    toc: true



